// @ts-check
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';
import rehypeExternalLinks from 'rehype-external-links';
import remarkWikilinks from './plugins/remark-wikilinks.mjs';
import {
  ENABLED_LANGUAGE_CODES,
  DEFAULT_LANGUAGE,
} from './src/config/languages.mjs';
import { readdirSync, statSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { resolveRedirectTargets } from './scripts/core/resolve-redirect-targets.mjs';

// 2026-04-24 β3: Build existing URL set from src/content/ to filter sitemap
// hreflang alternate to only include actually-existing language versions.
// Without this, @astrojs/sitemap auto-generates hreflang for ALL enabled
// locales for EVERY page — causing 1,705+ fake hreflang URLs (Google crawls
// them → 404 → SC reports 404). This pre-build scan + serialize() hook fix
// the systemic SEO leak.
//
// URL mapping convention:
//   src/content/{lang}/{category}/{slug}.md →
//     {lang === 'zh-TW' ? '' : '/' + lang}/{category}/{slug}/
function buildExistingUrlSet() {
  const set = new Set();
  const contentRoot = './src/content';
  for (const lang of ENABLED_LANGUAGE_CODES) {
    const langPath = join(contentRoot, lang);
    if (!existsSync(langPath)) continue;
    let cats;
    try {
      cats = readdirSync(langPath);
    } catch {
      continue;
    }
    for (const cat of cats) {
      const catPath = join(langPath, cat);
      let isDir = false;
      try {
        isDir = statSync(catPath).isDirectory();
      } catch {
        continue;
      }
      if (!isDir) continue;
      let files;
      try {
        files = readdirSync(catPath);
      } catch {
        continue;
      }
      for (const f of files) {
        if (!f.endsWith('.md')) continue;
        if (f.startsWith('_')) continue; // skip _Hub etc
        const slug = f.replace(/\.md$/, '');
        const prefix = lang === DEFAULT_LANGUAGE.code ? '' : `/${lang}`;
        set.add(`${prefix}/${cat}/${slug}/`);
      }
    }
    // Also add language landing pages (/en/, /ja/, /ko/) and zh-TW root
    const prefix = lang === DEFAULT_LANGUAGE.code ? '/' : `/${lang}/`;
    set.add(prefix);
  }
  return set;
}

const existingUrlSet = buildExistingUrlSet();
console.log(
  `[sitemap-hreflang-filter] Loaded ${existingUrlSet.size} existing URL paths for hreflang validation`,
);

// 2026-07-25 article-alias：英文別名網址集合，給 sitemap serialize() 排除用。
// 別名本身是真實存在的頁面（0 秒轉址殼），所以它不會變成死連結；要防的是
// 反向風險——把側門公告成正門。詳見 scripts/core/generate-article-aliases.mjs。
function buildAliasUrlSet() {
  const set = new Set();
  const p = './config/article-aliases.json';
  if (!existsSync(p)) return set;
  try {
    for (const key of Object.keys(JSON.parse(readFileSync(p, 'utf-8')))) {
      set.add(`/${key}/`);
    }
  } catch (err) {
    // 讀壞了要出聲，不要靜默讓別名漏進 sitemap。
    console.warn('[sitemap-alias-filter] article-aliases.json 讀取失敗：', err);
  }
  return set;
}
const aliasUrlSet = buildAliasUrlSet();
console.log(
  `[sitemap-alias-filter] Loaded ${aliasUrlSet.size} alias URLs to exclude from sitemap`,
);

// Build sitemap i18n locales map: { 'zh-TW': 'zh-TW', en: 'en', ... }
const sitemapLocales = Object.fromEntries(
  ENABLED_LANGUAGE_CODES.map((code) => [code, code]),
);

// 2026-04-18 δ-late: Semiont pages are zh-TW-only (meta-layer, not translated).
// Header nav's translatePath() generates /en/semiont/*, /ja/semiont/*, /ko/semiont/*
// etc. even though those routes don't exist — causing systemic 404s.
// Smart redirect: individual cognitive-organ pages (manifesto/dna/anatomy/...) are
// zh-TW canonical (they change weekly as the Semiont evolves its own self-model,
// translation would go stale). Redirect their non-zh paths to canonical zh-TW.
//
// 2026-04-21 γ: `/semiont` (landing) now has a real /en/ page via i18n semiont.ts,
// so it's removed from this list. If ja/ko landing pages are added later, also
// remove `/semiont` from non-default-lang redirects or gate by lang here.
// /semiont/diary has its own en page (but entries are zh-TW only, template shows notice).
const SEMIONT_ROUTES = [
  '/semiont/manifesto',
  '/semiont/dna',
  '/semiont/anatomy',
  '/semiont/consciousness',
  '/semiont/heartbeat',
  '/semiont/unknowns',
  '/semiont/longings',
  '/semiont/diary', // entries are zh-TW only; landing notice points readers there
];
const NON_DEFAULT_LANGS = ENABLED_LANGUAGE_CODES.filter(
  (c) => c !== DEFAULT_LANGUAGE.code,
);
const semiontRedirects = Object.fromEntries(
  NON_DEFAULT_LANGS.flatMap((lang) =>
    SEMIONT_ROUTES.map((route) => [`/${lang}${route}`, `${route}/`]),
  ),
);

// 2026-06-07 SEO freshness (reports/seo-optimization-plan-2026-06-07.md §1.1):
// Per-URL sitemap <lastmod> from real last-meaningful-commit dates, generated by
// scripts/core/build-content-dates.mjs (git-derived, cosmetic-filtered). Replaces
// the old global `lastmod: new Date()` which made Google distrust our lastmod.
let contentDates = {};
try {
  contentDates =
    JSON.parse(readFileSync('./src/data/content-dates.json', 'utf-8')).dates ||
    {};
} catch {
  // not yet generated → omit lastmod entirely (safe; never fake-fresh)
}

export default defineConfig({
  site: 'https://computex.taiwanai.ngo',
  integrations: [
    sitemap({
      changefreq: 'weekly',
      priority: 0.7,
      // 2026-06-07: global `lastmod: new Date()` REMOVED — it made every page
      // claim "modified today" on every build, the exact anti-pattern Google
      // names (→ distrusts our lastmod site-wide). lastmod is now set per-URL in
      // serialize() from content-dates.json. See SEO plan report §1.1.
      // Customize priority and changefreq for different pages
      customPages: [
        'https://computex.taiwanai.ngo/?changefreq=daily&priority=1.0',
        'https://computex.taiwanai.ngo/en?changefreq=daily&priority=1.0',
      ],
      i18n: {
        defaultLocale: DEFAULT_LANGUAGE.code,
        locales: sitemapLocales,
      },
      // 2026-04-24 β3: Filter hreflang alternate links to only include
      // actually-existing language versions. Without this filter,
      // @astrojs/sitemap auto-generates alternate hreflang for ALL enabled
      // locales for EVERY page—even when the target language version doesn't
      // exist—causing systemic 404s reported in Search Console.
      //
      // Pre-fix data: 3,031 hreflang tags vs 1,800 actual content files
      //   → 1,705 fake hreflang (en +675 / ja +432 / ko +598)
      //
      // serialize() runs per sitemap item before XML emission. We filter
      // item.links to only include alternates whose path exists in
      // existingUrlSet (built from src/content/ filesystem scan above).
      serialize(item) {
        // 2026-07-25 article-alias：英文別名側門一律不進 sitemap。別名是給
        // 「照著我們自己的 URL 文法推網址」的人跟機器走的側門，不是第二個正門
        // ——canonical 永遠是中文網址。放進 sitemap 等於請 Google 把同一篇文章
        // 當兩個 URL 收，正是 2026-07-17 那次 15% 404 率的同科病（站體對外
        // 公告了自己不打算負責的 URL）。SSOT 是 config/article-aliases.json。
        try {
          if (aliasUrlSet.has(decodeURIComponent(new URL(item.url).pathname)))
            return undefined;
        } catch {
          /* malformed URL：交給下面既有的處理 */
        }
        // Per-URL <lastmod> = real last meaningful edit (content-dates.json,
        // git-derived + cosmetic-filtered). Omit when unknown — never fake.
        // decodeURIComponent: sitemap loc percent-encodes CJK slugs (zh-TW
        // articles), but content-dates keys are raw UTF-8 — decode to match.
        try {
          const lm =
            contentDates[decodeURIComponent(new URL(item.url).pathname)];
          if (lm) item.lastmod = lm;
          else delete item.lastmod;
        } catch {
          delete item.lastmod;
        }
        if (!item.links || item.links.length === 0) return item;
        const filteredLinks = item.links.filter((link) => {
          try {
            const path = new URL(link.url).pathname;
            return existingUrlSet.has(path);
          } catch {
            // Malformed URL; drop conservatively
            return false;
          }
        });
        // Astro types: links is optional; empty array is fine but undefined
        // signals "no alternate" cleanly
        item.links = filteredLinks.length > 0 ? filteredLinks : undefined;
        return item;
      },
    }),
  ],
  i18n: {
    defaultLocale: DEFAULT_LANGUAGE.code,
    locales: [...ENABLED_LANGUAGE_CODES],
    routing: {
      prefixDefaultLocale: false,
    },
  },
  // 2026-04-11 heartbeat: Static redirects for top 404 URLs identified via
  // Cloudflare logs. Astro generates HTML meta-refresh pages for each entry.
  // Review with: bash scripts/tools/fetch-cloudflare.py --days 1
  //
  // 2026-07-17: generated redirects merged in from config/redirects-generated
  // .json (slug-unification renames + monitor-404 observed dead URLs with
  // resolvable targets; producer: scripts/core/generate-redirects.mjs, runs in
  // prebuild). Deploy platform truth is GitHub Pages — _redirects files are
  // NOT supported there, meta-refresh stubs are the only native redirect path.
  // Inline entries below win on key collision (spread order).
  //
  // 2026-07-24: 整張表過 resolveRedirectTargets() existence-aware 解析 —
  // 語言文章型目標的譯文被 quarantine 暫時刪除時，stub canonical 會指向
  // 404 直接紅 CI（同日連炸四次部署）。目標缺席 → 退 zh canonical，
  // 譯文補回後下次 build 自動恢復直達。詳 scripts/core/resolve-redirect-targets.mjs。
  redirects: resolveRedirectTargets({
    // 母體的台灣文章 redirect map 已整段移除（SPECIATION Stage 2）。
    // 本站自己的 slug 改名 redirect 從這裡累積；generated 的仍由 prebuild 併入。
    ...(existsSync('./config/redirects-generated.json')
      ? JSON.parse(readFileSync('./config/redirects-generated.json', 'utf-8'))
      : {}),
  }),
  // 2026-05-04: build perf tuning. Page render is 93% of build time
  // (363s render / 391s wall, baseline 4,331 pages). concurrency 1 → 4
  // is the highest-ROI lever; details in reports/research/astro-build-speed-2026-05-04.md.
  // 2026-06-10 audit A/B: 8,436 頁 / 943s render，有效平行度 3.08/4 → 試 8。
  // heap 已 12GB；下個 CI build 看 wall + RSS，OOM/變慢即回退 4。
  // reports/build-pipeline-audit-2026-06-10.md 熱點 #2a。
  build: {
    concurrency: 8,
    inlineStylesheets: 'auto',
  },
  markdown: {
    // Explicit lang allowlist. Knowledge corpus uses bare ``` fences almost
    // exclusively (1 named lang in src/content), so capping the loaded grammar
    // bundle to common ones keeps Shiki startup small without breaking pages.
    shikiConfig: {
      theme: 'github-light',
      wrap: true,
      langs: [
        'ts',
        'tsx',
        'js',
        'jsx',
        'astro',
        'bash',
        'sh',
        'md',
        'json',
        'yaml',
        'html',
        'css',
        'python',
        'go',
        'rust',
        'sql',
        'diff',
        'plaintext',
      ],
    },
    remarkPlugins: [remarkWikilinks],
    rehypePlugins: [
      [
        rehypeExternalLinks,
        { target: '_blank', rel: ['noopener', 'noreferrer'] },
      ],
    ],
  },
  vite: {
    plugins: [tailwindcss()],
    build: {
      target: 'es2022',
      minify: 'esbuild',
      cssCodeSplit: true,
      chunkSizeWarningLimit: 10000,
      rollupOptions: {
        output: {
          // For huge SSG (4k+ pages) Rollup spends measurable time computing
          // chunk splits when the per-route bundle is tiny. Forcing one-chunk
          // output is faster on this scale (per bitdoze 339k-page case study).
          manualChunks: undefined,
        },
      },
    },
    esbuild: {
      target: 'es2022',
      minifyIdentifiers: false,
      minifySyntax: true,
      minifyWhitespace: true,
    },
    optimizeDeps: { force: false },
  },
  // experimental.queuedRendering tested 2026-05-04 — local wallclock unchanged,
  // peak RSS 1.7 GB → 4.3 GB (poolSize: 1000 over-allocates for diverse pages).
  // Skipping until upstream tunes pool sizing for content-heavy SSG.
});
